// 2023-01-03 config.h
// Copyright (C) 2023 Vino Fernando Crescini  <vfcrescini@gmail.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef _CAMWEBSRV_CONFIG_H
#define _CAMWEBSRV_CONFIG_H

#define CAMWEBSRV_TAG "camwebsrv"

#define CAMWEBSRV_MAIN_REBOOT_DELAY_MSEC 10000
#define CAMWEBSRV_MAIN_MIN_CYCLE_MSEC 10

#define CAMWEBSRV_CFGMAN_FILENAME "config.cfg"
#define CAMWEBSRV_CFGMAN_KEY_WIFI_SSID "wifi_ssid"
#define CAMWEBSRV_CFGMAN_KEY_WIFI_PASS "wifi_pass"
#define CAMWEBSRV_CFGMAN_KEY_PING_HOST "ping_host"
#define CAMWEBSRV_CFGMAN_KEY_PAIR_ID "pair_id"
#define CAMWEBSRV_CFGMAN_KEY_ROLE "role"

#define CAMWEBSRV_CAMERA_INITIAL_FRAME_SKIP 3
#define CAMWEBSRV_CAMERA_FPS_MIN 1
#define CAMWEBSRV_CAMERA_FPS_MAX 8
#define CAMWEBSRV_CAMERA_DEFAULT_FS 10
#define CAMWEBSRV_CAMERA_DEFAULT_FPS 4
#define CAMWEBSRV_CAMERA_DEFAULT_FLASH false

#define CAMWEBSRV_VBYTES_BSIZE 16

#define CAMWEBSRV_SCLIENTS_BSIZE 8192
#define CAMWEBSRV_SCLIENTS_SEND_TMOUT 1000
#define CAMWEBSRV_SCLIENTS_IDLE_TMOUT 3000

#define CAMWEBSRV_PING_TIMEOUT_MAX 3
#define CAMWEBSRV_PING_TIMEOUT_SEND 5000
#define CAMWEBSRV_PING_TIMEOUT_RECV 5000
#define CAMWEBSRV_PING_WAIT_INTERVAL 1000
#define CAMWEBSRV_PING_CYCLE_INTERVAL 30000

// ESP32Cam (AiThinker) PIN Map

#define CAMWEBSRV_PIN_PWDN 32
#define CAMWEBSRV_PIN_RESET -1
#define CAMWEBSRV_PIN_XCLK 0
#define CAMWEBSRV_PIN_SIOD 26
#define CAMWEBSRV_PIN_SIOC 27

#define CAMWEBSRV_PIN_D7 35
#define CAMWEBSRV_PIN_D6 34
#define CAMWEBSRV_PIN_D5 39
#define CAMWEBSRV_PIN_D4 36
#define CAMWEBSRV_PIN_D3 21
#define CAMWEBSRV_PIN_D2 19
#define CAMWEBSRV_PIN_D1 18
#define CAMWEBSRV_PIN_D0 5
#define CAMWEBSRV_PIN_VSYNC 25
#define CAMWEBSRV_PIN_HREF 23
#define CAMWEBSRV_PIN_PCLK 22

#define CAMWEBSRV_PIN_FLASH 33

// Sequence capture sync signal pin (master output, slave interrupt input)
#define CAMWEBSRV_PIN_SYNC 16

// SDMMC (SDIO) 4-bit pin map for ESP32-CAM (AiThinker)
// NOTE: GPIO4 is shared with the onboard flash LED on many ESP32-CAM boards.
// If you use 4-bit SDMMC, you typically can't use the flash LED while SD is mounted.
#define CAMWEBSRV_SDMMC_PIN_CLK 14
#define CAMWEBSRV_SDMMC_PIN_CMD 15
#define CAMWEBSRV_SDMMC_PIN_D0  2
#define CAMWEBSRV_SDMMC_PIN_D1  4
#define CAMWEBSRV_SDMMC_PIN_D2  12
#define CAMWEBSRV_SDMMC_PIN_D3  13

// SD card mount point for captures
#define CAMWEBSRV_SDCARD_MOUNT_PATH "/sdcard"
#define SD_WRITE_BUFFER_SIZE_KB 16


#endif
